runtime: python39
entrypoint: bash startup.sh

instance_class: F4

env_variables:
  DAGSTER_HOME: "/tmp"

includes:
  - env_variables.yaml

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1